title: Ricardo Jaimes Hernandez
description: Cybersecurity Portfolio

url: "https://rickjaimesdez.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-feed

collections:
  writeups:
    output: true
    permalink: /writeups/:name/
    nav_exclude: true   # Hides writeup files from the navbar

defaults:
  - scope:
      path: "_writeups"
      type: writeups
    values:
      layout: page
      nav_exclude: true   # Double protection
