title: Ricardo Jaimes Hernandez
description: Cybersecurity Portfolio

url: "https://rickjaimesdez.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-feed

  navbar:
  - title: Projects
    url: /projects/
  - title: Skills
    url: /skills/
  - title: Certifications
    url: /certifications/
  - title: Contact
    url: /contact/


